### ISSUE TITLE
根据作者提供的代码库无法跑出论文中写的结果

### ISSUE THREAD

**Issue by shukhg** [kybinn/DrugDoctor#3]
您好！

首先，非常感谢您分享这个有价值的项目。最近我在尝试复现您论文中的实验结果时，发现了一些小的不同之处。具体来说，我注意到在几个关键指标上，我的实验结果与论文中报告的结果有大约1%到1.5%的差距。例如 MIMIC-Ⅲ 的 AUC 我仅能跑出 0.678

我知道这些差异可能是由多种因素引起的，比如不同的运行环境或者依赖库的版本等。为了确保大家可以更准确地复现您的研究结果，不知道是否有计划更新一下代码库呢？这将有助于社区成员更好地理解和使用您的工作成果。

祝好

**Comment by kybinn** [comment]
首先谢谢你的关注。
我能够肯定的是，您在实现中一定存在某些问题，可能是代码经过修改，可能是实验平台环境等等。

下面是之前issue2中一个研究者的运行结果。
epoch 22 --------------------------

DDI Rate: 0.07488, Jaccard: 0.527, PRAUC: 0.7791, AVG_PRC: 0.6702, AVG_RECALL: 0.7221, AVG_F1: 0.6823, AVG_MED: 21.78
training time: 60.72959494590759, test time: 10.172691106796265
best_epoch: 22


基于您的结果 0.678 和这位研究者的结果 0.7791，**明显看到二者的差别。**
我不打算更新代码中的参数，因为您的结果和这位研究者的提供的数据也相差较大。
二者的实现上肯定是不一致的。我无法做到让每个人都能实现出模型的最佳效果。

我不清楚是什么具体原因导致您的实现存在较大差异。其实我建议从论文/代码中学习和拿到自己最需要的东西去利用。
像我在实现 MoleRec，SHAPE，COGNet 等等方法时，都无法获得与原文一致的结果，但上述方法依然对我帮助很大。
我并不打算修改研究代码或参数，因为我们现在正在基于这篇文章提出的方法，有了新的研究进展。我的建议：您可以利用visit-level的代码，自己修改model.py部分设计自己的模型，祝取得好的性能。

再次谢谢你的关注。加油、

**Comment by shukhg** [comment]
> 首先谢谢你的关注。 我能够肯定的是，您在实现中一定存在某些问题，可能是代码经过修改，可能是实验平台环境等等。
> 
> 下面是之前issue2中一个研究者的运行结果。 epoch 22 --------------------------
> 
> DDI Rate: 0.07488, Jaccard: 0.527, PRAUC: 0.7791, AVG_PRC: 0.6702, AVG_RECALL: 0.7221, AVG_F1: 0.6823, AVG_MED: 21.78 training time: 60.72959494590759, test time: 10.172691106796265 best_epoch: 22
> 
> 基于您的结果 0.678 和这位研究者的结果 0.7791，**明显看到二者的差别。** 我不打算更新代码中的参数，因为您的结果和这位研究者的提供的数据也相差较大。 二者的实现上肯定是不一致的。我无法做到让每个人都能实现出模型的最佳效果。
> 
> 我不清楚是什么具体原因导致您的实现存在较大差异。其实我建议从论文/代码中学习和拿到自己最需要的东西去利用。 像我在实现 MoleRec，SHAPE，COGNet 等等方法时，都无法获得与原文一致的结果，但上述方法依然对我帮助很大。 我并不打算修改研究代码或参数，因为我们现在正在基于这篇文章提出的方法，有了新的研究进展。我的建议：您可以利用visit-level的代码，自己修改model.py部分设计自己的模型，祝取得好的性能。
> 
> 再次谢谢你的关注。加油、

这里是我写错了，不是 AUC，而是 F1。  就算是这个 issue2，也与您论文中写的结果存在一点的差异。   您的代码对这个领域的发展会有重要的意义，如果您有时间还是恳求您对代码进行修正。   祝愿您多发论文！
